export function formDataPaciente(form, foto) {
	let nuevoUsuario = new FormData()
	nuevoUsuario.append('nombre', form.nombre.value)
	nuevoUsuario.append('fechaDeNac', form.fechaDeNac.value)
	nuevoUsuario.append('cedula', form.cedula.value)
	nuevoUsuario.append('edad', form.edad.value)
	nuevoUsuario.append('sociedad', form.sociedad.value)
	nuevoUsuario.append('telefono', form.telefono.value)
	nuevoUsuario.append('nombreContacto2', form.nombreContacto2.value)
	nuevoUsuario.append('telefonoContacto2', form.telefonoContacto2.value)
	nuevoUsuario.append('alimentacion', form.alimentacion.value)
	nuevoUsuario.append('descanso', form.descanso.value)
	nuevoUsuario.append('hidratacion', form.hidratacion.value)
	nuevoUsuario.append('alcohol', form.alcohol.value)
	nuevoUsuario.append('fuma', form.fuma.value)
	nuevoUsuario.append('alergia', form.alergia.value)
	nuevoUsuario.append('circulatorio', form.circulatorio.value)
	nuevoUsuario.append('embarazo', form.embarazo.value)
	nuevoUsuario.append('operaciones', form.operaciones.value)
	nuevoUsuario.append('oncologicas', form.oncologicas.value)
	nuevoUsuario.append('enfermedades', form.enfermedades.value)
	nuevoUsuario.append('medicamentos', form.medicamentos.value)
	nuevoUsuario.append('implantes', form.implantes.value)
	nuevoUsuario.append('tratamiento', form.tratamiento.value)
	nuevoUsuario.append('observaciones', form.observaciones.value)
	nuevoUsuario.append('foto', foto)
	return nuevoUsuario
}
