export function formDataPaciente(values) {
  let nuevoUsuario = new FormData()
  nuevoUsuario.append('nombre', values.nombre)
  nuevoUsuario.append('fechaDeNac', values.fechaDeNac)
  nuevoUsuario.append('cedula', values.cedula)
  nuevoUsuario.append('edad', values.edad)
  nuevoUsuario.append('sociedad', values.sociedad)
  nuevoUsuario.append('telefono', values.telefono)
  nuevoUsuario.append('nombreContacto2', values.nombreContacto2)
  nuevoUsuario.append('telefonoContacto2', values.telefonoContacto2)
  nuevoUsuario.append('alimentacion', values.alimentacion)
  nuevoUsuario.append('descanso', values.descanso)
  nuevoUsuario.append('hidratacion', values.hidratacion)
  nuevoUsuario.append('alcohol', values.alcohol)
  nuevoUsuario.append('fuma', values.fuma)
  nuevoUsuario.append('alergia', values.alergia)
  nuevoUsuario.append('circulatorio', values.circulatorio)
  nuevoUsuario.append('embarazo', values.embarazo)
  nuevoUsuario.append('operaciones', values.operaciones)
  nuevoUsuario.append('oncologicas', values.oncologicas)
  nuevoUsuario.append('enfermedades', values.enfermedades)
  nuevoUsuario.append('medicamentos', values.medicamentos)
  nuevoUsuario.append('implantes', values.implantes)
  nuevoUsuario.append('tratamiento', values.tratamiento)
  nuevoUsuario.append('servicio', values.servicio)
  nuevoUsuario.append('observaciones', values.observaciones)
  nuevoUsuario.append('foto', values.foto)
  return nuevoUsuario
}
